### ISSUE TITLE
Example: copy/paste

### ISSUE THREAD

**Issue by guest271314** [medooze/libdatachannels#2]
When you find the time can you kindly create a basic copy/paste example?

**Comment by murillo128** [comment]
Unfortunately, the library is not fully operational yet. I plan to start working again on it soon, but don't have an ETA for when it would be functional.

**Comment by guest271314** [comment]
This https://github.com/paullouisageneau/libdatachannel works. Just trying to test your gear, which appears to be slightly smaller. I'll check back here periodically.

**Comment by murillo128** [comment]
seems it is using usersctp under the hood, which i really want to avoid.

Have you checked Google’s new datachannels lib?

**Comment by guest271314** [comment]
I assess data channels as a "black box", unobservable, yet works. My use case is purely local - execute arbitrary shell scripts and programs from the browser and stream stdout to the browser, without writing and files to do so, so it does not really matter how the communication is achieved.

No, I havn't checked out Googles new data channel lib. The last time I checked WebRTC official library was far too immense to download and build (especially on machines where I only run on RAM with minimal disk space). Native Messaging alone and a local server with `fetch()` work quite well for my use cases https://github.com/guest271314/native-messaging-php. 

The purpose of testing data channels is to compare working Native Messaging with C++ (25KB). I really don;t think there is a comparison as to source code necessary capture and stream live audio https://github.com/guest271314/captureSystemAudio/blob/master/native_messaging/capture_system_audio/capture_system_audio.cpp.

**Comment by guest271314** [comment]
> Have you checked Google’s new datachannels lib?

Link? So that I can find precisely what you are referencing?

**Comment by murillo128** [comment]
https://chromium.googlesource.com/external/webrtc/+/master/net/dcsctp

**Comment by guest271314** [comment]
Thanks. I'll have to read how to build and use that for testing/comparison.

> seems it is using usersctp under the hood, which i really want to avoid.

Why? Less secure? Slower than what you prefer to use? What is novel about Google's new data channel implementation? 

Does that make a difference for my use cases (purely local capture of system audio and arbitrary shell script and program execution - that I can then stream using WebRTC in the browser) for data channels?
